
name:                                     Databricks Deployment

trigger:                                  none
pr:                                       none



# TO DO : Retrofit This Code So You Can Choose The Environments You Want To Deploy. This Will be
# Helpfull if a Release Pipeline Fails And We Need To Rewind The Commit And Redeploy

# Create A Condition That This Will Not Run When A Pull Request Is Launched. Presumably a CI only Condition
# After The First Environment Deployment, This YAML Pipeline is Triggering Alongside onRealease. I have Set
# pr == none For Now To Prevent This Behaviour 


pool:
  vmImage:                                'ubuntu-latest'

#Secrets
variables:
- group:                                    'ADO-Secrets'

stages:
  
  - stage:                                SandboxDeploy                                   
    displayName:                          SandboxDeploy
    jobs:
      - template:                         ..\2-Jobs\jobDatabricks.yaml
        parameters:
          Environment:                    Sandbox
          azureSubscription:              DBX_ADO_DSTOOLKIT
          enableRepoPull:                 false
          branchName:                     main
  
#  - stage:                                DevelopmentDeploy                                   
#    displayName:                          DevelopmentDeploy
#    dependsOn: [] 
#    jobs:
#      - template:                         ..\2-Jobs\jobDatabricks.yaml
#        parameters:
#          Environment:                    Development
#          azureSubscription:              DBX_ADO_DSTOOLKIT
#          enableRepoPull:                 false
#          branchName:                     main
#          updateFolder:                   None

#  - stage:                                UATDeploy                                   
#    displayName:                          UATDeploy
#    dependsOn: [] 
#    jobs:
#      - template:                         ..\2-Jobs\jobDatabricks.yaml
#        parameters:
#          Environment:                    UAT
#          azureSubscription:              DBX_ADO_DSTOOLKIT
#          enableRepoPull:                 false
#          branchName:                     main
#          releaseBranch:                  'release/1'